name: "GCP on-demand container scan"
description: "Scan container using GCP"


inputs:
  container_name:
    description: "Container name tag which we want to scan"
    required: true
  slackWebhook:
    description: "Preferred slack channel webhook to send notifications"
    required: true
runs:
  using: composite
  steps:
    - name: Container Scan
      run: ./scripts/scan.sh
      shell: bash
